/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KwcAlert {
    }
    interface KwcArrowLeftIcon {
    }
    interface KwcButton {
    }
    interface KwcCard {
    }
    interface KwcCheckCircleIcon {
    }
    interface KwcCheckIcon {
    }
    interface KwcCloseCircleFilledIcon {
    }
    interface KwcCloseCircleIcon {
    }
    interface KwcCloseIcon {
    }
    interface KwcCode {
    }
    interface KwcContactsIcon {
    }
    interface KwcCopyButton {
    }
    interface KwcCopyIcon {
    }
    interface KwcDeleteIcon {
    }
    interface KwcDescriptionItem {
    }
    interface KwcDescriptions {
    }
    interface KwcDivider {
    }
    interface KwcDotChartIcon {
    }
    interface KwcDownIcon {
    }
    interface KwcEmpty {
    }
    interface KwcEmptyIcon {
    }
    interface KwcExclamationCircleIcon {
    }
    interface KwcFundProjectionScreenIcon {
    }
    interface KwcGlobalIcon {
    }
    interface KwcInfoBox {
    }
    interface KwcInfoBoxGrid {
    }
    interface KwcInfoCircleIcon {
    }
    interface KwcInput {
    }
    interface KwcList {
    }
    interface KwcLoadingIcon {
    }
    interface KwcMinusSquareIcon {
    }
    interface KwcModal {
    }
    interface KwcModalContent {
    }
    interface KwcNewTabIcon {
    }
    interface KwcOption {
    }
    interface KwcPagination {
    }
    interface KwcPartitionIcon {
    }
    interface KwcPercentageIcon {
    }
    interface KwcPieChartIcon {
    }
    interface KwcPlusSquareIcon {
    }
    interface KwcPortalCreator {
    }
    interface KwcQuestionCircleIcon {
    }
    interface KwcReloadIcon {
    }
    interface KwcRightIcon {
    }
    interface KwcSearchIcon {
    }
    interface KwcSelect {
    }
    interface KwcSelectOptions {
    }
    interface KwcShareIcon {
    }
    interface KwcStopIcon {
    }
    interface KwcSyncIcon {
    }
    interface KwcTab {
    }
    interface KwcTabs {
    }
    interface KwcTag {
    }
    interface KwcTeamIcon {
    }
    interface KwcTooltip {
    }
    interface KwcTooltipContainer {
    }
    interface KwcUpIcon {
    }
    interface KwcUserIcon {
    }
    interface KwcUsergroupDeleteIcon {
    }
    interface KwcVerticalAlignBottomIcon {
    }
    interface KwcVerticalAlignTopIcon {
    }
    interface KwcWarningIcon {
    }
}
declare global {
    interface HTMLKwcAlertElement extends Components.KwcAlert, HTMLStencilElement {
    }
    var HTMLKwcAlertElement: {
        prototype: HTMLKwcAlertElement;
        new (): HTMLKwcAlertElement;
    };
    interface HTMLKwcArrowLeftIconElement extends Components.KwcArrowLeftIcon, HTMLStencilElement {
    }
    var HTMLKwcArrowLeftIconElement: {
        prototype: HTMLKwcArrowLeftIconElement;
        new (): HTMLKwcArrowLeftIconElement;
    };
    interface HTMLKwcButtonElement extends Components.KwcButton, HTMLStencilElement {
    }
    var HTMLKwcButtonElement: {
        prototype: HTMLKwcButtonElement;
        new (): HTMLKwcButtonElement;
    };
    interface HTMLKwcCardElement extends Components.KwcCard, HTMLStencilElement {
    }
    var HTMLKwcCardElement: {
        prototype: HTMLKwcCardElement;
        new (): HTMLKwcCardElement;
    };
    interface HTMLKwcCheckCircleIconElement extends Components.KwcCheckCircleIcon, HTMLStencilElement {
    }
    var HTMLKwcCheckCircleIconElement: {
        prototype: HTMLKwcCheckCircleIconElement;
        new (): HTMLKwcCheckCircleIconElement;
    };
    interface HTMLKwcCheckIconElement extends Components.KwcCheckIcon, HTMLStencilElement {
    }
    var HTMLKwcCheckIconElement: {
        prototype: HTMLKwcCheckIconElement;
        new (): HTMLKwcCheckIconElement;
    };
    interface HTMLKwcCloseCircleFilledIconElement extends Components.KwcCloseCircleFilledIcon, HTMLStencilElement {
    }
    var HTMLKwcCloseCircleFilledIconElement: {
        prototype: HTMLKwcCloseCircleFilledIconElement;
        new (): HTMLKwcCloseCircleFilledIconElement;
    };
    interface HTMLKwcCloseCircleIconElement extends Components.KwcCloseCircleIcon, HTMLStencilElement {
    }
    var HTMLKwcCloseCircleIconElement: {
        prototype: HTMLKwcCloseCircleIconElement;
        new (): HTMLKwcCloseCircleIconElement;
    };
    interface HTMLKwcCloseIconElement extends Components.KwcCloseIcon, HTMLStencilElement {
    }
    var HTMLKwcCloseIconElement: {
        prototype: HTMLKwcCloseIconElement;
        new (): HTMLKwcCloseIconElement;
    };
    interface HTMLKwcCodeElement extends Components.KwcCode, HTMLStencilElement {
    }
    var HTMLKwcCodeElement: {
        prototype: HTMLKwcCodeElement;
        new (): HTMLKwcCodeElement;
    };
    interface HTMLKwcContactsIconElement extends Components.KwcContactsIcon, HTMLStencilElement {
    }
    var HTMLKwcContactsIconElement: {
        prototype: HTMLKwcContactsIconElement;
        new (): HTMLKwcContactsIconElement;
    };
    interface HTMLKwcCopyButtonElement extends Components.KwcCopyButton, HTMLStencilElement {
    }
    var HTMLKwcCopyButtonElement: {
        prototype: HTMLKwcCopyButtonElement;
        new (): HTMLKwcCopyButtonElement;
    };
    interface HTMLKwcCopyIconElement extends Components.KwcCopyIcon, HTMLStencilElement {
    }
    var HTMLKwcCopyIconElement: {
        prototype: HTMLKwcCopyIconElement;
        new (): HTMLKwcCopyIconElement;
    };
    interface HTMLKwcDeleteIconElement extends Components.KwcDeleteIcon, HTMLStencilElement {
    }
    var HTMLKwcDeleteIconElement: {
        prototype: HTMLKwcDeleteIconElement;
        new (): HTMLKwcDeleteIconElement;
    };
    interface HTMLKwcDescriptionItemElement extends Components.KwcDescriptionItem, HTMLStencilElement {
    }
    var HTMLKwcDescriptionItemElement: {
        prototype: HTMLKwcDescriptionItemElement;
        new (): HTMLKwcDescriptionItemElement;
    };
    interface HTMLKwcDescriptionsElement extends Components.KwcDescriptions, HTMLStencilElement {
    }
    var HTMLKwcDescriptionsElement: {
        prototype: HTMLKwcDescriptionsElement;
        new (): HTMLKwcDescriptionsElement;
    };
    interface HTMLKwcDividerElement extends Components.KwcDivider, HTMLStencilElement {
    }
    var HTMLKwcDividerElement: {
        prototype: HTMLKwcDividerElement;
        new (): HTMLKwcDividerElement;
    };
    interface HTMLKwcDotChartIconElement extends Components.KwcDotChartIcon, HTMLStencilElement {
    }
    var HTMLKwcDotChartIconElement: {
        prototype: HTMLKwcDotChartIconElement;
        new (): HTMLKwcDotChartIconElement;
    };
    interface HTMLKwcDownIconElement extends Components.KwcDownIcon, HTMLStencilElement {
    }
    var HTMLKwcDownIconElement: {
        prototype: HTMLKwcDownIconElement;
        new (): HTMLKwcDownIconElement;
    };
    interface HTMLKwcEmptyElement extends Components.KwcEmpty, HTMLStencilElement {
    }
    var HTMLKwcEmptyElement: {
        prototype: HTMLKwcEmptyElement;
        new (): HTMLKwcEmptyElement;
    };
    interface HTMLKwcEmptyIconElement extends Components.KwcEmptyIcon, HTMLStencilElement {
    }
    var HTMLKwcEmptyIconElement: {
        prototype: HTMLKwcEmptyIconElement;
        new (): HTMLKwcEmptyIconElement;
    };
    interface HTMLKwcExclamationCircleIconElement extends Components.KwcExclamationCircleIcon, HTMLStencilElement {
    }
    var HTMLKwcExclamationCircleIconElement: {
        prototype: HTMLKwcExclamationCircleIconElement;
        new (): HTMLKwcExclamationCircleIconElement;
    };
    interface HTMLKwcFundProjectionScreenIconElement extends Components.KwcFundProjectionScreenIcon, HTMLStencilElement {
    }
    var HTMLKwcFundProjectionScreenIconElement: {
        prototype: HTMLKwcFundProjectionScreenIconElement;
        new (): HTMLKwcFundProjectionScreenIconElement;
    };
    interface HTMLKwcGlobalIconElement extends Components.KwcGlobalIcon, HTMLStencilElement {
    }
    var HTMLKwcGlobalIconElement: {
        prototype: HTMLKwcGlobalIconElement;
        new (): HTMLKwcGlobalIconElement;
    };
    interface HTMLKwcInfoBoxElement extends Components.KwcInfoBox, HTMLStencilElement {
    }
    var HTMLKwcInfoBoxElement: {
        prototype: HTMLKwcInfoBoxElement;
        new (): HTMLKwcInfoBoxElement;
    };
    interface HTMLKwcInfoBoxGridElement extends Components.KwcInfoBoxGrid, HTMLStencilElement {
    }
    var HTMLKwcInfoBoxGridElement: {
        prototype: HTMLKwcInfoBoxGridElement;
        new (): HTMLKwcInfoBoxGridElement;
    };
    interface HTMLKwcInfoCircleIconElement extends Components.KwcInfoCircleIcon, HTMLStencilElement {
    }
    var HTMLKwcInfoCircleIconElement: {
        prototype: HTMLKwcInfoCircleIconElement;
        new (): HTMLKwcInfoCircleIconElement;
    };
    interface HTMLKwcInputElement extends Components.KwcInput, HTMLStencilElement {
    }
    var HTMLKwcInputElement: {
        prototype: HTMLKwcInputElement;
        new (): HTMLKwcInputElement;
    };
    interface HTMLKwcListElement extends Components.KwcList, HTMLStencilElement {
    }
    var HTMLKwcListElement: {
        prototype: HTMLKwcListElement;
        new (): HTMLKwcListElement;
    };
    interface HTMLKwcLoadingIconElement extends Components.KwcLoadingIcon, HTMLStencilElement {
    }
    var HTMLKwcLoadingIconElement: {
        prototype: HTMLKwcLoadingIconElement;
        new (): HTMLKwcLoadingIconElement;
    };
    interface HTMLKwcMinusSquareIconElement extends Components.KwcMinusSquareIcon, HTMLStencilElement {
    }
    var HTMLKwcMinusSquareIconElement: {
        prototype: HTMLKwcMinusSquareIconElement;
        new (): HTMLKwcMinusSquareIconElement;
    };
    interface HTMLKwcModalElement extends Components.KwcModal, HTMLStencilElement {
    }
    var HTMLKwcModalElement: {
        prototype: HTMLKwcModalElement;
        new (): HTMLKwcModalElement;
    };
    interface HTMLKwcModalContentElement extends Components.KwcModalContent, HTMLStencilElement {
    }
    var HTMLKwcModalContentElement: {
        prototype: HTMLKwcModalContentElement;
        new (): HTMLKwcModalContentElement;
    };
    interface HTMLKwcNewTabIconElement extends Components.KwcNewTabIcon, HTMLStencilElement {
    }
    var HTMLKwcNewTabIconElement: {
        prototype: HTMLKwcNewTabIconElement;
        new (): HTMLKwcNewTabIconElement;
    };
    interface HTMLKwcOptionElement extends Components.KwcOption, HTMLStencilElement {
    }
    var HTMLKwcOptionElement: {
        prototype: HTMLKwcOptionElement;
        new (): HTMLKwcOptionElement;
    };
    interface HTMLKwcPaginationElement extends Components.KwcPagination, HTMLStencilElement {
    }
    var HTMLKwcPaginationElement: {
        prototype: HTMLKwcPaginationElement;
        new (): HTMLKwcPaginationElement;
    };
    interface HTMLKwcPartitionIconElement extends Components.KwcPartitionIcon, HTMLStencilElement {
    }
    var HTMLKwcPartitionIconElement: {
        prototype: HTMLKwcPartitionIconElement;
        new (): HTMLKwcPartitionIconElement;
    };
    interface HTMLKwcPercentageIconElement extends Components.KwcPercentageIcon, HTMLStencilElement {
    }
    var HTMLKwcPercentageIconElement: {
        prototype: HTMLKwcPercentageIconElement;
        new (): HTMLKwcPercentageIconElement;
    };
    interface HTMLKwcPieChartIconElement extends Components.KwcPieChartIcon, HTMLStencilElement {
    }
    var HTMLKwcPieChartIconElement: {
        prototype: HTMLKwcPieChartIconElement;
        new (): HTMLKwcPieChartIconElement;
    };
    interface HTMLKwcPlusSquareIconElement extends Components.KwcPlusSquareIcon, HTMLStencilElement {
    }
    var HTMLKwcPlusSquareIconElement: {
        prototype: HTMLKwcPlusSquareIconElement;
        new (): HTMLKwcPlusSquareIconElement;
    };
    interface HTMLKwcPortalCreatorElement extends Components.KwcPortalCreator, HTMLStencilElement {
    }
    var HTMLKwcPortalCreatorElement: {
        prototype: HTMLKwcPortalCreatorElement;
        new (): HTMLKwcPortalCreatorElement;
    };
    interface HTMLKwcQuestionCircleIconElement extends Components.KwcQuestionCircleIcon, HTMLStencilElement {
    }
    var HTMLKwcQuestionCircleIconElement: {
        prototype: HTMLKwcQuestionCircleIconElement;
        new (): HTMLKwcQuestionCircleIconElement;
    };
    interface HTMLKwcReloadIconElement extends Components.KwcReloadIcon, HTMLStencilElement {
    }
    var HTMLKwcReloadIconElement: {
        prototype: HTMLKwcReloadIconElement;
        new (): HTMLKwcReloadIconElement;
    };
    interface HTMLKwcRightIconElement extends Components.KwcRightIcon, HTMLStencilElement {
    }
    var HTMLKwcRightIconElement: {
        prototype: HTMLKwcRightIconElement;
        new (): HTMLKwcRightIconElement;
    };
    interface HTMLKwcSearchIconElement extends Components.KwcSearchIcon, HTMLStencilElement {
    }
    var HTMLKwcSearchIconElement: {
        prototype: HTMLKwcSearchIconElement;
        new (): HTMLKwcSearchIconElement;
    };
    interface HTMLKwcSelectElement extends Components.KwcSelect, HTMLStencilElement {
    }
    var HTMLKwcSelectElement: {
        prototype: HTMLKwcSelectElement;
        new (): HTMLKwcSelectElement;
    };
    interface HTMLKwcSelectOptionsElement extends Components.KwcSelectOptions, HTMLStencilElement {
    }
    var HTMLKwcSelectOptionsElement: {
        prototype: HTMLKwcSelectOptionsElement;
        new (): HTMLKwcSelectOptionsElement;
    };
    interface HTMLKwcShareIconElement extends Components.KwcShareIcon, HTMLStencilElement {
    }
    var HTMLKwcShareIconElement: {
        prototype: HTMLKwcShareIconElement;
        new (): HTMLKwcShareIconElement;
    };
    interface HTMLKwcStopIconElement extends Components.KwcStopIcon, HTMLStencilElement {
    }
    var HTMLKwcStopIconElement: {
        prototype: HTMLKwcStopIconElement;
        new (): HTMLKwcStopIconElement;
    };
    interface HTMLKwcSyncIconElement extends Components.KwcSyncIcon, HTMLStencilElement {
    }
    var HTMLKwcSyncIconElement: {
        prototype: HTMLKwcSyncIconElement;
        new (): HTMLKwcSyncIconElement;
    };
    interface HTMLKwcTabElement extends Components.KwcTab, HTMLStencilElement {
    }
    var HTMLKwcTabElement: {
        prototype: HTMLKwcTabElement;
        new (): HTMLKwcTabElement;
    };
    interface HTMLKwcTabsElement extends Components.KwcTabs, HTMLStencilElement {
    }
    var HTMLKwcTabsElement: {
        prototype: HTMLKwcTabsElement;
        new (): HTMLKwcTabsElement;
    };
    interface HTMLKwcTagElement extends Components.KwcTag, HTMLStencilElement {
    }
    var HTMLKwcTagElement: {
        prototype: HTMLKwcTagElement;
        new (): HTMLKwcTagElement;
    };
    interface HTMLKwcTeamIconElement extends Components.KwcTeamIcon, HTMLStencilElement {
    }
    var HTMLKwcTeamIconElement: {
        prototype: HTMLKwcTeamIconElement;
        new (): HTMLKwcTeamIconElement;
    };
    interface HTMLKwcTooltipElement extends Components.KwcTooltip, HTMLStencilElement {
    }
    var HTMLKwcTooltipElement: {
        prototype: HTMLKwcTooltipElement;
        new (): HTMLKwcTooltipElement;
    };
    interface HTMLKwcTooltipContainerElement extends Components.KwcTooltipContainer, HTMLStencilElement {
    }
    var HTMLKwcTooltipContainerElement: {
        prototype: HTMLKwcTooltipContainerElement;
        new (): HTMLKwcTooltipContainerElement;
    };
    interface HTMLKwcUpIconElement extends Components.KwcUpIcon, HTMLStencilElement {
    }
    var HTMLKwcUpIconElement: {
        prototype: HTMLKwcUpIconElement;
        new (): HTMLKwcUpIconElement;
    };
    interface HTMLKwcUserIconElement extends Components.KwcUserIcon, HTMLStencilElement {
    }
    var HTMLKwcUserIconElement: {
        prototype: HTMLKwcUserIconElement;
        new (): HTMLKwcUserIconElement;
    };
    interface HTMLKwcUsergroupDeleteIconElement extends Components.KwcUsergroupDeleteIcon, HTMLStencilElement {
    }
    var HTMLKwcUsergroupDeleteIconElement: {
        prototype: HTMLKwcUsergroupDeleteIconElement;
        new (): HTMLKwcUsergroupDeleteIconElement;
    };
    interface HTMLKwcVerticalAlignBottomIconElement extends Components.KwcVerticalAlignBottomIcon, HTMLStencilElement {
    }
    var HTMLKwcVerticalAlignBottomIconElement: {
        prototype: HTMLKwcVerticalAlignBottomIconElement;
        new (): HTMLKwcVerticalAlignBottomIconElement;
    };
    interface HTMLKwcVerticalAlignTopIconElement extends Components.KwcVerticalAlignTopIcon, HTMLStencilElement {
    }
    var HTMLKwcVerticalAlignTopIconElement: {
        prototype: HTMLKwcVerticalAlignTopIconElement;
        new (): HTMLKwcVerticalAlignTopIconElement;
    };
    interface HTMLKwcWarningIconElement extends Components.KwcWarningIcon, HTMLStencilElement {
    }
    var HTMLKwcWarningIconElement: {
        prototype: HTMLKwcWarningIconElement;
        new (): HTMLKwcWarningIconElement;
    };
    interface HTMLElementTagNameMap {
        "kwc-alert": HTMLKwcAlertElement;
        "kwc-arrow-left-icon": HTMLKwcArrowLeftIconElement;
        "kwc-button": HTMLKwcButtonElement;
        "kwc-card": HTMLKwcCardElement;
        "kwc-check-circle-icon": HTMLKwcCheckCircleIconElement;
        "kwc-check-icon": HTMLKwcCheckIconElement;
        "kwc-close-circle-filled-icon": HTMLKwcCloseCircleFilledIconElement;
        "kwc-close-circle-icon": HTMLKwcCloseCircleIconElement;
        "kwc-close-icon": HTMLKwcCloseIconElement;
        "kwc-code": HTMLKwcCodeElement;
        "kwc-contacts-icon": HTMLKwcContactsIconElement;
        "kwc-copy-button": HTMLKwcCopyButtonElement;
        "kwc-copy-icon": HTMLKwcCopyIconElement;
        "kwc-delete-icon": HTMLKwcDeleteIconElement;
        "kwc-description-item": HTMLKwcDescriptionItemElement;
        "kwc-descriptions": HTMLKwcDescriptionsElement;
        "kwc-divider": HTMLKwcDividerElement;
        "kwc-dot-chart-icon": HTMLKwcDotChartIconElement;
        "kwc-down-icon": HTMLKwcDownIconElement;
        "kwc-empty": HTMLKwcEmptyElement;
        "kwc-empty-icon": HTMLKwcEmptyIconElement;
        "kwc-exclamation-circle-icon": HTMLKwcExclamationCircleIconElement;
        "kwc-fund-projection-screen-icon": HTMLKwcFundProjectionScreenIconElement;
        "kwc-global-icon": HTMLKwcGlobalIconElement;
        "kwc-info-box": HTMLKwcInfoBoxElement;
        "kwc-info-box-grid": HTMLKwcInfoBoxGridElement;
        "kwc-info-circle-icon": HTMLKwcInfoCircleIconElement;
        "kwc-input": HTMLKwcInputElement;
        "kwc-list": HTMLKwcListElement;
        "kwc-loading-icon": HTMLKwcLoadingIconElement;
        "kwc-minus-square-icon": HTMLKwcMinusSquareIconElement;
        "kwc-modal": HTMLKwcModalElement;
        "kwc-modal-content": HTMLKwcModalContentElement;
        "kwc-new-tab-icon": HTMLKwcNewTabIconElement;
        "kwc-option": HTMLKwcOptionElement;
        "kwc-pagination": HTMLKwcPaginationElement;
        "kwc-partition-icon": HTMLKwcPartitionIconElement;
        "kwc-percentage-icon": HTMLKwcPercentageIconElement;
        "kwc-pie-chart-icon": HTMLKwcPieChartIconElement;
        "kwc-plus-square-icon": HTMLKwcPlusSquareIconElement;
        "kwc-portal-creator": HTMLKwcPortalCreatorElement;
        "kwc-question-circle-icon": HTMLKwcQuestionCircleIconElement;
        "kwc-reload-icon": HTMLKwcReloadIconElement;
        "kwc-right-icon": HTMLKwcRightIconElement;
        "kwc-search-icon": HTMLKwcSearchIconElement;
        "kwc-select": HTMLKwcSelectElement;
        "kwc-select-options": HTMLKwcSelectOptionsElement;
        "kwc-share-icon": HTMLKwcShareIconElement;
        "kwc-stop-icon": HTMLKwcStopIconElement;
        "kwc-sync-icon": HTMLKwcSyncIconElement;
        "kwc-tab": HTMLKwcTabElement;
        "kwc-tabs": HTMLKwcTabsElement;
        "kwc-tag": HTMLKwcTagElement;
        "kwc-team-icon": HTMLKwcTeamIconElement;
        "kwc-tooltip": HTMLKwcTooltipElement;
        "kwc-tooltip-container": HTMLKwcTooltipContainerElement;
        "kwc-up-icon": HTMLKwcUpIconElement;
        "kwc-user-icon": HTMLKwcUserIconElement;
        "kwc-usergroup-delete-icon": HTMLKwcUsergroupDeleteIconElement;
        "kwc-vertical-align-bottom-icon": HTMLKwcVerticalAlignBottomIconElement;
        "kwc-vertical-align-top-icon": HTMLKwcVerticalAlignTopIconElement;
        "kwc-warning-icon": HTMLKwcWarningIconElement;
    }
}
declare namespace LocalJSX {
    interface KwcAlert {
    }
    interface KwcArrowLeftIcon {
    }
    interface KwcButton {
    }
    interface KwcCard {
    }
    interface KwcCheckCircleIcon {
    }
    interface KwcCheckIcon {
    }
    interface KwcCloseCircleFilledIcon {
    }
    interface KwcCloseCircleIcon {
    }
    interface KwcCloseIcon {
    }
    interface KwcCode {
    }
    interface KwcContactsIcon {
    }
    interface KwcCopyButton {
    }
    interface KwcCopyIcon {
    }
    interface KwcDeleteIcon {
    }
    interface KwcDescriptionItem {
    }
    interface KwcDescriptions {
    }
    interface KwcDivider {
    }
    interface KwcDotChartIcon {
    }
    interface KwcDownIcon {
    }
    interface KwcEmpty {
    }
    interface KwcEmptyIcon {
    }
    interface KwcExclamationCircleIcon {
    }
    interface KwcFundProjectionScreenIcon {
    }
    interface KwcGlobalIcon {
    }
    interface KwcInfoBox {
    }
    interface KwcInfoBoxGrid {
    }
    interface KwcInfoCircleIcon {
    }
    interface KwcInput {
    }
    interface KwcList {
    }
    interface KwcLoadingIcon {
    }
    interface KwcMinusSquareIcon {
    }
    interface KwcModal {
    }
    interface KwcModalContent {
    }
    interface KwcNewTabIcon {
    }
    interface KwcOption {
    }
    interface KwcPagination {
    }
    interface KwcPartitionIcon {
    }
    interface KwcPercentageIcon {
    }
    interface KwcPieChartIcon {
    }
    interface KwcPlusSquareIcon {
    }
    interface KwcPortalCreator {
    }
    interface KwcQuestionCircleIcon {
    }
    interface KwcReloadIcon {
    }
    interface KwcRightIcon {
    }
    interface KwcSearchIcon {
    }
    interface KwcSelect {
    }
    interface KwcSelectOptions {
    }
    interface KwcShareIcon {
    }
    interface KwcStopIcon {
    }
    interface KwcSyncIcon {
    }
    interface KwcTab {
    }
    interface KwcTabs {
    }
    interface KwcTag {
    }
    interface KwcTeamIcon {
    }
    interface KwcTooltip {
    }
    interface KwcTooltipContainer {
    }
    interface KwcUpIcon {
    }
    interface KwcUserIcon {
    }
    interface KwcUsergroupDeleteIcon {
    }
    interface KwcVerticalAlignBottomIcon {
    }
    interface KwcVerticalAlignTopIcon {
    }
    interface KwcWarningIcon {
    }
    interface IntrinsicElements {
        "kwc-alert": KwcAlert;
        "kwc-arrow-left-icon": KwcArrowLeftIcon;
        "kwc-button": KwcButton;
        "kwc-card": KwcCard;
        "kwc-check-circle-icon": KwcCheckCircleIcon;
        "kwc-check-icon": KwcCheckIcon;
        "kwc-close-circle-filled-icon": KwcCloseCircleFilledIcon;
        "kwc-close-circle-icon": KwcCloseCircleIcon;
        "kwc-close-icon": KwcCloseIcon;
        "kwc-code": KwcCode;
        "kwc-contacts-icon": KwcContactsIcon;
        "kwc-copy-button": KwcCopyButton;
        "kwc-copy-icon": KwcCopyIcon;
        "kwc-delete-icon": KwcDeleteIcon;
        "kwc-description-item": KwcDescriptionItem;
        "kwc-descriptions": KwcDescriptions;
        "kwc-divider": KwcDivider;
        "kwc-dot-chart-icon": KwcDotChartIcon;
        "kwc-down-icon": KwcDownIcon;
        "kwc-empty": KwcEmpty;
        "kwc-empty-icon": KwcEmptyIcon;
        "kwc-exclamation-circle-icon": KwcExclamationCircleIcon;
        "kwc-fund-projection-screen-icon": KwcFundProjectionScreenIcon;
        "kwc-global-icon": KwcGlobalIcon;
        "kwc-info-box": KwcInfoBox;
        "kwc-info-box-grid": KwcInfoBoxGrid;
        "kwc-info-circle-icon": KwcInfoCircleIcon;
        "kwc-input": KwcInput;
        "kwc-list": KwcList;
        "kwc-loading-icon": KwcLoadingIcon;
        "kwc-minus-square-icon": KwcMinusSquareIcon;
        "kwc-modal": KwcModal;
        "kwc-modal-content": KwcModalContent;
        "kwc-new-tab-icon": KwcNewTabIcon;
        "kwc-option": KwcOption;
        "kwc-pagination": KwcPagination;
        "kwc-partition-icon": KwcPartitionIcon;
        "kwc-percentage-icon": KwcPercentageIcon;
        "kwc-pie-chart-icon": KwcPieChartIcon;
        "kwc-plus-square-icon": KwcPlusSquareIcon;
        "kwc-portal-creator": KwcPortalCreator;
        "kwc-question-circle-icon": KwcQuestionCircleIcon;
        "kwc-reload-icon": KwcReloadIcon;
        "kwc-right-icon": KwcRightIcon;
        "kwc-search-icon": KwcSearchIcon;
        "kwc-select": KwcSelect;
        "kwc-select-options": KwcSelectOptions;
        "kwc-share-icon": KwcShareIcon;
        "kwc-stop-icon": KwcStopIcon;
        "kwc-sync-icon": KwcSyncIcon;
        "kwc-tab": KwcTab;
        "kwc-tabs": KwcTabs;
        "kwc-tag": KwcTag;
        "kwc-team-icon": KwcTeamIcon;
        "kwc-tooltip": KwcTooltip;
        "kwc-tooltip-container": KwcTooltipContainer;
        "kwc-up-icon": KwcUpIcon;
        "kwc-user-icon": KwcUserIcon;
        "kwc-usergroup-delete-icon": KwcUsergroupDeleteIcon;
        "kwc-vertical-align-bottom-icon": KwcVerticalAlignBottomIcon;
        "kwc-vertical-align-top-icon": KwcVerticalAlignTopIcon;
        "kwc-warning-icon": KwcWarningIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kwc-alert": LocalJSX.KwcAlert & JSXBase.HTMLAttributes<HTMLKwcAlertElement>;
            "kwc-arrow-left-icon": LocalJSX.KwcArrowLeftIcon & JSXBase.HTMLAttributes<HTMLKwcArrowLeftIconElement>;
            "kwc-button": LocalJSX.KwcButton & JSXBase.HTMLAttributes<HTMLKwcButtonElement>;
            "kwc-card": LocalJSX.KwcCard & JSXBase.HTMLAttributes<HTMLKwcCardElement>;
            "kwc-check-circle-icon": LocalJSX.KwcCheckCircleIcon & JSXBase.HTMLAttributes<HTMLKwcCheckCircleIconElement>;
            "kwc-check-icon": LocalJSX.KwcCheckIcon & JSXBase.HTMLAttributes<HTMLKwcCheckIconElement>;
            "kwc-close-circle-filled-icon": LocalJSX.KwcCloseCircleFilledIcon & JSXBase.HTMLAttributes<HTMLKwcCloseCircleFilledIconElement>;
            "kwc-close-circle-icon": LocalJSX.KwcCloseCircleIcon & JSXBase.HTMLAttributes<HTMLKwcCloseCircleIconElement>;
            "kwc-close-icon": LocalJSX.KwcCloseIcon & JSXBase.HTMLAttributes<HTMLKwcCloseIconElement>;
            "kwc-code": LocalJSX.KwcCode & JSXBase.HTMLAttributes<HTMLKwcCodeElement>;
            "kwc-contacts-icon": LocalJSX.KwcContactsIcon & JSXBase.HTMLAttributes<HTMLKwcContactsIconElement>;
            "kwc-copy-button": LocalJSX.KwcCopyButton & JSXBase.HTMLAttributes<HTMLKwcCopyButtonElement>;
            "kwc-copy-icon": LocalJSX.KwcCopyIcon & JSXBase.HTMLAttributes<HTMLKwcCopyIconElement>;
            "kwc-delete-icon": LocalJSX.KwcDeleteIcon & JSXBase.HTMLAttributes<HTMLKwcDeleteIconElement>;
            "kwc-description-item": LocalJSX.KwcDescriptionItem & JSXBase.HTMLAttributes<HTMLKwcDescriptionItemElement>;
            "kwc-descriptions": LocalJSX.KwcDescriptions & JSXBase.HTMLAttributes<HTMLKwcDescriptionsElement>;
            "kwc-divider": LocalJSX.KwcDivider & JSXBase.HTMLAttributes<HTMLKwcDividerElement>;
            "kwc-dot-chart-icon": LocalJSX.KwcDotChartIcon & JSXBase.HTMLAttributes<HTMLKwcDotChartIconElement>;
            "kwc-down-icon": LocalJSX.KwcDownIcon & JSXBase.HTMLAttributes<HTMLKwcDownIconElement>;
            "kwc-empty": LocalJSX.KwcEmpty & JSXBase.HTMLAttributes<HTMLKwcEmptyElement>;
            "kwc-empty-icon": LocalJSX.KwcEmptyIcon & JSXBase.HTMLAttributes<HTMLKwcEmptyIconElement>;
            "kwc-exclamation-circle-icon": LocalJSX.KwcExclamationCircleIcon & JSXBase.HTMLAttributes<HTMLKwcExclamationCircleIconElement>;
            "kwc-fund-projection-screen-icon": LocalJSX.KwcFundProjectionScreenIcon & JSXBase.HTMLAttributes<HTMLKwcFundProjectionScreenIconElement>;
            "kwc-global-icon": LocalJSX.KwcGlobalIcon & JSXBase.HTMLAttributes<HTMLKwcGlobalIconElement>;
            "kwc-info-box": LocalJSX.KwcInfoBox & JSXBase.HTMLAttributes<HTMLKwcInfoBoxElement>;
            "kwc-info-box-grid": LocalJSX.KwcInfoBoxGrid & JSXBase.HTMLAttributes<HTMLKwcInfoBoxGridElement>;
            "kwc-info-circle-icon": LocalJSX.KwcInfoCircleIcon & JSXBase.HTMLAttributes<HTMLKwcInfoCircleIconElement>;
            "kwc-input": LocalJSX.KwcInput & JSXBase.HTMLAttributes<HTMLKwcInputElement>;
            "kwc-list": LocalJSX.KwcList & JSXBase.HTMLAttributes<HTMLKwcListElement>;
            "kwc-loading-icon": LocalJSX.KwcLoadingIcon & JSXBase.HTMLAttributes<HTMLKwcLoadingIconElement>;
            "kwc-minus-square-icon": LocalJSX.KwcMinusSquareIcon & JSXBase.HTMLAttributes<HTMLKwcMinusSquareIconElement>;
            "kwc-modal": LocalJSX.KwcModal & JSXBase.HTMLAttributes<HTMLKwcModalElement>;
            "kwc-modal-content": LocalJSX.KwcModalContent & JSXBase.HTMLAttributes<HTMLKwcModalContentElement>;
            "kwc-new-tab-icon": LocalJSX.KwcNewTabIcon & JSXBase.HTMLAttributes<HTMLKwcNewTabIconElement>;
            "kwc-option": LocalJSX.KwcOption & JSXBase.HTMLAttributes<HTMLKwcOptionElement>;
            "kwc-pagination": LocalJSX.KwcPagination & JSXBase.HTMLAttributes<HTMLKwcPaginationElement>;
            "kwc-partition-icon": LocalJSX.KwcPartitionIcon & JSXBase.HTMLAttributes<HTMLKwcPartitionIconElement>;
            "kwc-percentage-icon": LocalJSX.KwcPercentageIcon & JSXBase.HTMLAttributes<HTMLKwcPercentageIconElement>;
            "kwc-pie-chart-icon": LocalJSX.KwcPieChartIcon & JSXBase.HTMLAttributes<HTMLKwcPieChartIconElement>;
            "kwc-plus-square-icon": LocalJSX.KwcPlusSquareIcon & JSXBase.HTMLAttributes<HTMLKwcPlusSquareIconElement>;
            "kwc-portal-creator": LocalJSX.KwcPortalCreator & JSXBase.HTMLAttributes<HTMLKwcPortalCreatorElement>;
            "kwc-question-circle-icon": LocalJSX.KwcQuestionCircleIcon & JSXBase.HTMLAttributes<HTMLKwcQuestionCircleIconElement>;
            "kwc-reload-icon": LocalJSX.KwcReloadIcon & JSXBase.HTMLAttributes<HTMLKwcReloadIconElement>;
            "kwc-right-icon": LocalJSX.KwcRightIcon & JSXBase.HTMLAttributes<HTMLKwcRightIconElement>;
            "kwc-search-icon": LocalJSX.KwcSearchIcon & JSXBase.HTMLAttributes<HTMLKwcSearchIconElement>;
            "kwc-select": LocalJSX.KwcSelect & JSXBase.HTMLAttributes<HTMLKwcSelectElement>;
            "kwc-select-options": LocalJSX.KwcSelectOptions & JSXBase.HTMLAttributes<HTMLKwcSelectOptionsElement>;
            "kwc-share-icon": LocalJSX.KwcShareIcon & JSXBase.HTMLAttributes<HTMLKwcShareIconElement>;
            "kwc-stop-icon": LocalJSX.KwcStopIcon & JSXBase.HTMLAttributes<HTMLKwcStopIconElement>;
            "kwc-sync-icon": LocalJSX.KwcSyncIcon & JSXBase.HTMLAttributes<HTMLKwcSyncIconElement>;
            "kwc-tab": LocalJSX.KwcTab & JSXBase.HTMLAttributes<HTMLKwcTabElement>;
            "kwc-tabs": LocalJSX.KwcTabs & JSXBase.HTMLAttributes<HTMLKwcTabsElement>;
            "kwc-tag": LocalJSX.KwcTag & JSXBase.HTMLAttributes<HTMLKwcTagElement>;
            "kwc-team-icon": LocalJSX.KwcTeamIcon & JSXBase.HTMLAttributes<HTMLKwcTeamIconElement>;
            "kwc-tooltip": LocalJSX.KwcTooltip & JSXBase.HTMLAttributes<HTMLKwcTooltipElement>;
            "kwc-tooltip-container": LocalJSX.KwcTooltipContainer & JSXBase.HTMLAttributes<HTMLKwcTooltipContainerElement>;
            "kwc-up-icon": LocalJSX.KwcUpIcon & JSXBase.HTMLAttributes<HTMLKwcUpIconElement>;
            "kwc-user-icon": LocalJSX.KwcUserIcon & JSXBase.HTMLAttributes<HTMLKwcUserIconElement>;
            "kwc-usergroup-delete-icon": LocalJSX.KwcUsergroupDeleteIcon & JSXBase.HTMLAttributes<HTMLKwcUsergroupDeleteIconElement>;
            "kwc-vertical-align-bottom-icon": LocalJSX.KwcVerticalAlignBottomIcon & JSXBase.HTMLAttributes<HTMLKwcVerticalAlignBottomIconElement>;
            "kwc-vertical-align-top-icon": LocalJSX.KwcVerticalAlignTopIcon & JSXBase.HTMLAttributes<HTMLKwcVerticalAlignTopIconElement>;
            "kwc-warning-icon": LocalJSX.KwcWarningIcon & JSXBase.HTMLAttributes<HTMLKwcWarningIconElement>;
        }
    }
}
