/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UspAutocomplete {
    }
    interface UspAutocompleteContainer {
    }
    interface UspBasePopulationSelect {
    }
    interface UspEditorIframeWrapper {
    }
    interface UspIsUserInSegment {
    }
    interface UspKqlAnalyser {
    }
    interface UspKqlAnalyserLink {
    }
    interface UspKqlDiff {
    }
    interface UspKqlDiffModal {
    }
    interface UspKqlEditor {
    }
    interface UspKqlHelp {
    }
    interface UspKqlHelpWidget {
    }
    interface UspPopulationCounter {
    }
    interface UspPopulationDrilldown {
    }
    interface UspPopulationInsights {
    }
    interface UspPopulationSampling {
    }
    interface UspQueryBuilder {
    }
    interface UspQueryBuilderEditor {
    }
    interface UspQueryBuilderLegacy {
    }
    interface UspSingleKqlDiff {
    }
    interface UspTextInput {
    }
    interface UspUserDetails {
    }
    interface UspUserSampling {
    }
}
declare global {
    interface HTMLUspAutocompleteElement extends Components.UspAutocomplete, HTMLStencilElement {
    }
    var HTMLUspAutocompleteElement: {
        prototype: HTMLUspAutocompleteElement;
        new (): HTMLUspAutocompleteElement;
    };
    interface HTMLUspAutocompleteContainerElement extends Components.UspAutocompleteContainer, HTMLStencilElement {
    }
    var HTMLUspAutocompleteContainerElement: {
        prototype: HTMLUspAutocompleteContainerElement;
        new (): HTMLUspAutocompleteContainerElement;
    };
    interface HTMLUspBasePopulationSelectElement extends Components.UspBasePopulationSelect, HTMLStencilElement {
    }
    var HTMLUspBasePopulationSelectElement: {
        prototype: HTMLUspBasePopulationSelectElement;
        new (): HTMLUspBasePopulationSelectElement;
    };
    interface HTMLUspEditorIframeWrapperElement extends Components.UspEditorIframeWrapper, HTMLStencilElement {
    }
    var HTMLUspEditorIframeWrapperElement: {
        prototype: HTMLUspEditorIframeWrapperElement;
        new (): HTMLUspEditorIframeWrapperElement;
    };
    interface HTMLUspIsUserInSegmentElement extends Components.UspIsUserInSegment, HTMLStencilElement {
    }
    var HTMLUspIsUserInSegmentElement: {
        prototype: HTMLUspIsUserInSegmentElement;
        new (): HTMLUspIsUserInSegmentElement;
    };
    interface HTMLUspKqlAnalyserElement extends Components.UspKqlAnalyser, HTMLStencilElement {
    }
    var HTMLUspKqlAnalyserElement: {
        prototype: HTMLUspKqlAnalyserElement;
        new (): HTMLUspKqlAnalyserElement;
    };
    interface HTMLUspKqlAnalyserLinkElement extends Components.UspKqlAnalyserLink, HTMLStencilElement {
    }
    var HTMLUspKqlAnalyserLinkElement: {
        prototype: HTMLUspKqlAnalyserLinkElement;
        new (): HTMLUspKqlAnalyserLinkElement;
    };
    interface HTMLUspKqlDiffElement extends Components.UspKqlDiff, HTMLStencilElement {
    }
    var HTMLUspKqlDiffElement: {
        prototype: HTMLUspKqlDiffElement;
        new (): HTMLUspKqlDiffElement;
    };
    interface HTMLUspKqlDiffModalElement extends Components.UspKqlDiffModal, HTMLStencilElement {
    }
    var HTMLUspKqlDiffModalElement: {
        prototype: HTMLUspKqlDiffModalElement;
        new (): HTMLUspKqlDiffModalElement;
    };
    interface HTMLUspKqlEditorElement extends Components.UspKqlEditor, HTMLStencilElement {
    }
    var HTMLUspKqlEditorElement: {
        prototype: HTMLUspKqlEditorElement;
        new (): HTMLUspKqlEditorElement;
    };
    interface HTMLUspKqlHelpElement extends Components.UspKqlHelp, HTMLStencilElement {
    }
    var HTMLUspKqlHelpElement: {
        prototype: HTMLUspKqlHelpElement;
        new (): HTMLUspKqlHelpElement;
    };
    interface HTMLUspKqlHelpWidgetElement extends Components.UspKqlHelpWidget, HTMLStencilElement {
    }
    var HTMLUspKqlHelpWidgetElement: {
        prototype: HTMLUspKqlHelpWidgetElement;
        new (): HTMLUspKqlHelpWidgetElement;
    };
    interface HTMLUspPopulationCounterElement extends Components.UspPopulationCounter, HTMLStencilElement {
    }
    var HTMLUspPopulationCounterElement: {
        prototype: HTMLUspPopulationCounterElement;
        new (): HTMLUspPopulationCounterElement;
    };
    interface HTMLUspPopulationDrilldownElement extends Components.UspPopulationDrilldown, HTMLStencilElement {
    }
    var HTMLUspPopulationDrilldownElement: {
        prototype: HTMLUspPopulationDrilldownElement;
        new (): HTMLUspPopulationDrilldownElement;
    };
    interface HTMLUspPopulationInsightsElement extends Components.UspPopulationInsights, HTMLStencilElement {
    }
    var HTMLUspPopulationInsightsElement: {
        prototype: HTMLUspPopulationInsightsElement;
        new (): HTMLUspPopulationInsightsElement;
    };
    interface HTMLUspPopulationSamplingElement extends Components.UspPopulationSampling, HTMLStencilElement {
    }
    var HTMLUspPopulationSamplingElement: {
        prototype: HTMLUspPopulationSamplingElement;
        new (): HTMLUspPopulationSamplingElement;
    };
    interface HTMLUspQueryBuilderElement extends Components.UspQueryBuilder, HTMLStencilElement {
    }
    var HTMLUspQueryBuilderElement: {
        prototype: HTMLUspQueryBuilderElement;
        new (): HTMLUspQueryBuilderElement;
    };
    interface HTMLUspQueryBuilderEditorElement extends Components.UspQueryBuilderEditor, HTMLStencilElement {
    }
    var HTMLUspQueryBuilderEditorElement: {
        prototype: HTMLUspQueryBuilderEditorElement;
        new (): HTMLUspQueryBuilderEditorElement;
    };
    interface HTMLUspQueryBuilderLegacyElement extends Components.UspQueryBuilderLegacy, HTMLStencilElement {
    }
    var HTMLUspQueryBuilderLegacyElement: {
        prototype: HTMLUspQueryBuilderLegacyElement;
        new (): HTMLUspQueryBuilderLegacyElement;
    };
    interface HTMLUspSingleKqlDiffElement extends Components.UspSingleKqlDiff, HTMLStencilElement {
    }
    var HTMLUspSingleKqlDiffElement: {
        prototype: HTMLUspSingleKqlDiffElement;
        new (): HTMLUspSingleKqlDiffElement;
    };
    interface HTMLUspTextInputElement extends Components.UspTextInput, HTMLStencilElement {
    }
    var HTMLUspTextInputElement: {
        prototype: HTMLUspTextInputElement;
        new (): HTMLUspTextInputElement;
    };
    interface HTMLUspUserDetailsElement extends Components.UspUserDetails, HTMLStencilElement {
    }
    var HTMLUspUserDetailsElement: {
        prototype: HTMLUspUserDetailsElement;
        new (): HTMLUspUserDetailsElement;
    };
    interface HTMLUspUserSamplingElement extends Components.UspUserSampling, HTMLStencilElement {
    }
    var HTMLUspUserSamplingElement: {
        prototype: HTMLUspUserSamplingElement;
        new (): HTMLUspUserSamplingElement;
    };
    interface HTMLElementTagNameMap {
        "usp-autocomplete": HTMLUspAutocompleteElement;
        "usp-autocomplete-container": HTMLUspAutocompleteContainerElement;
        "usp-base-population-select": HTMLUspBasePopulationSelectElement;
        "usp-editor-iframe-wrapper": HTMLUspEditorIframeWrapperElement;
        "usp-is-user-in-segment": HTMLUspIsUserInSegmentElement;
        "usp-kql-analyser": HTMLUspKqlAnalyserElement;
        "usp-kql-analyser-link": HTMLUspKqlAnalyserLinkElement;
        "usp-kql-diff": HTMLUspKqlDiffElement;
        "usp-kql-diff-modal": HTMLUspKqlDiffModalElement;
        "usp-kql-editor": HTMLUspKqlEditorElement;
        "usp-kql-help": HTMLUspKqlHelpElement;
        "usp-kql-help-widget": HTMLUspKqlHelpWidgetElement;
        "usp-population-counter": HTMLUspPopulationCounterElement;
        "usp-population-drilldown": HTMLUspPopulationDrilldownElement;
        "usp-population-insights": HTMLUspPopulationInsightsElement;
        "usp-population-sampling": HTMLUspPopulationSamplingElement;
        "usp-query-builder": HTMLUspQueryBuilderElement;
        "usp-query-builder-editor": HTMLUspQueryBuilderEditorElement;
        "usp-query-builder-legacy": HTMLUspQueryBuilderLegacyElement;
        "usp-single-kql-diff": HTMLUspSingleKqlDiffElement;
        "usp-text-input": HTMLUspTextInputElement;
        "usp-user-details": HTMLUspUserDetailsElement;
        "usp-user-sampling": HTMLUspUserSamplingElement;
    }
}
declare namespace LocalJSX {
    interface UspAutocomplete {
    }
    interface UspAutocompleteContainer {
    }
    interface UspBasePopulationSelect {
    }
    interface UspEditorIframeWrapper {
    }
    interface UspIsUserInSegment {
    }
    interface UspKqlAnalyser {
    }
    interface UspKqlAnalyserLink {
    }
    interface UspKqlDiff {
    }
    interface UspKqlDiffModal {
    }
    interface UspKqlEditor {
    }
    interface UspKqlHelp {
    }
    interface UspKqlHelpWidget {
    }
    interface UspPopulationCounter {
    }
    interface UspPopulationDrilldown {
    }
    interface UspPopulationInsights {
    }
    interface UspPopulationSampling {
    }
    interface UspQueryBuilder {
    }
    interface UspQueryBuilderEditor {
    }
    interface UspQueryBuilderLegacy {
    }
    interface UspSingleKqlDiff {
    }
    interface UspTextInput {
    }
    interface UspUserDetails {
    }
    interface UspUserSampling {
    }
    interface IntrinsicElements {
        "usp-autocomplete": UspAutocomplete;
        "usp-autocomplete-container": UspAutocompleteContainer;
        "usp-base-population-select": UspBasePopulationSelect;
        "usp-editor-iframe-wrapper": UspEditorIframeWrapper;
        "usp-is-user-in-segment": UspIsUserInSegment;
        "usp-kql-analyser": UspKqlAnalyser;
        "usp-kql-analyser-link": UspKqlAnalyserLink;
        "usp-kql-diff": UspKqlDiff;
        "usp-kql-diff-modal": UspKqlDiffModal;
        "usp-kql-editor": UspKqlEditor;
        "usp-kql-help": UspKqlHelp;
        "usp-kql-help-widget": UspKqlHelpWidget;
        "usp-population-counter": UspPopulationCounter;
        "usp-population-drilldown": UspPopulationDrilldown;
        "usp-population-insights": UspPopulationInsights;
        "usp-population-sampling": UspPopulationSampling;
        "usp-query-builder": UspQueryBuilder;
        "usp-query-builder-editor": UspQueryBuilderEditor;
        "usp-query-builder-legacy": UspQueryBuilderLegacy;
        "usp-single-kql-diff": UspSingleKqlDiff;
        "usp-text-input": UspTextInput;
        "usp-user-details": UspUserDetails;
        "usp-user-sampling": UspUserSampling;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "usp-autocomplete": LocalJSX.UspAutocomplete & JSXBase.HTMLAttributes<HTMLUspAutocompleteElement>;
            "usp-autocomplete-container": LocalJSX.UspAutocompleteContainer & JSXBase.HTMLAttributes<HTMLUspAutocompleteContainerElement>;
            "usp-base-population-select": LocalJSX.UspBasePopulationSelect & JSXBase.HTMLAttributes<HTMLUspBasePopulationSelectElement>;
            "usp-editor-iframe-wrapper": LocalJSX.UspEditorIframeWrapper & JSXBase.HTMLAttributes<HTMLUspEditorIframeWrapperElement>;
            "usp-is-user-in-segment": LocalJSX.UspIsUserInSegment & JSXBase.HTMLAttributes<HTMLUspIsUserInSegmentElement>;
            "usp-kql-analyser": LocalJSX.UspKqlAnalyser & JSXBase.HTMLAttributes<HTMLUspKqlAnalyserElement>;
            "usp-kql-analyser-link": LocalJSX.UspKqlAnalyserLink & JSXBase.HTMLAttributes<HTMLUspKqlAnalyserLinkElement>;
            "usp-kql-diff": LocalJSX.UspKqlDiff & JSXBase.HTMLAttributes<HTMLUspKqlDiffElement>;
            "usp-kql-diff-modal": LocalJSX.UspKqlDiffModal & JSXBase.HTMLAttributes<HTMLUspKqlDiffModalElement>;
            "usp-kql-editor": LocalJSX.UspKqlEditor & JSXBase.HTMLAttributes<HTMLUspKqlEditorElement>;
            "usp-kql-help": LocalJSX.UspKqlHelp & JSXBase.HTMLAttributes<HTMLUspKqlHelpElement>;
            "usp-kql-help-widget": LocalJSX.UspKqlHelpWidget & JSXBase.HTMLAttributes<HTMLUspKqlHelpWidgetElement>;
            "usp-population-counter": LocalJSX.UspPopulationCounter & JSXBase.HTMLAttributes<HTMLUspPopulationCounterElement>;
            "usp-population-drilldown": LocalJSX.UspPopulationDrilldown & JSXBase.HTMLAttributes<HTMLUspPopulationDrilldownElement>;
            "usp-population-insights": LocalJSX.UspPopulationInsights & JSXBase.HTMLAttributes<HTMLUspPopulationInsightsElement>;
            "usp-population-sampling": LocalJSX.UspPopulationSampling & JSXBase.HTMLAttributes<HTMLUspPopulationSamplingElement>;
            "usp-query-builder": LocalJSX.UspQueryBuilder & JSXBase.HTMLAttributes<HTMLUspQueryBuilderElement>;
            "usp-query-builder-editor": LocalJSX.UspQueryBuilderEditor & JSXBase.HTMLAttributes<HTMLUspQueryBuilderEditorElement>;
            "usp-query-builder-legacy": LocalJSX.UspQueryBuilderLegacy & JSXBase.HTMLAttributes<HTMLUspQueryBuilderLegacyElement>;
            "usp-single-kql-diff": LocalJSX.UspSingleKqlDiff & JSXBase.HTMLAttributes<HTMLUspSingleKqlDiffElement>;
            "usp-text-input": LocalJSX.UspTextInput & JSXBase.HTMLAttributes<HTMLUspTextInputElement>;
            "usp-user-details": LocalJSX.UspUserDetails & JSXBase.HTMLAttributes<HTMLUspUserDetailsElement>;
            "usp-user-sampling": LocalJSX.UspUserSampling & JSXBase.HTMLAttributes<HTMLUspUserSamplingElement>;
        }
    }
}
